### PR TITLE
feat: toggle 'Control+Space'

### PR DESCRIPTION
**Pull request by LangLangBart**
### description
- toogle the app with <kbd>⌃ Control</kbd> + <kbd>Space</kbd>

### CODE REVIEW

**Review by SilverMarcs — COMMENTED** [review]
Would it be possible to have this behaviour:

- [ ] when visible but no focus: focus the app
- [ ] when visible with focus: hide the app
- [ ] when invisible: show **and** focus the app

**Comment by SilverMarcs** [comment]
Closest I could get to that behavior was through this:

```
const handleShortcut = () => {
  if (mainWindow.isFocused()) {
    mainWindow.blur();
  } else {
    mainWindow.setAlwaysOnTop(true);
    mainWindow.show();
    mainWindow.focus();
    mainWindow.setAlwaysOnTop(false);
  }
};
```

Caveat is that mainWindow.blur() wont return focus to the previous window we were on. 

Using mainWindow.minimise() here doesnt work as expected. If window is currently hidden, pressing the shortcut only makes the window visible. Need to press shortcut again to make it focused.

**Comment by LangLangBart** [comment]
> *when visible but no focus: focus the app*
> *when visible with focus: hide the app*

```js
  globalShortcut.register("Control+Space", () => {
    if (mainWindow.isVisible() && mainWindow.isFocused())
      mainWindow.hide()
    else {
      mainWindow.show()
    }
  });
```

> *when invisible: show and focus the app*

By `focus` do you mean the cursor in the box ready to type?

**Comment by SilverMarcs** [comment]
> By `focus` do you mean the cursor in the box ready to type?

Would be nice but not sure how that could be implemented.

In this context, by focus I mean putting it in front of all other windows. If the app is currently not focused, pressing the shortcut should always focus it. Does it do that already? For me, .show() does not automatically focus the window (which is expected).

**Comment by LangLangBart** [comment]
- [Dash for macOS](https://kapeli.com/dash) can `focus` the cursor in the search field, I assume this is what you meant ?

**Comment by LangLangBart** [comment]
Okay, I wrote the comment from the command line at the same time you wrote yours. I understand your point of view. The behavior you described already works for me.

**Comment by SilverMarcs** [comment]
Ok yeah there was probably a bug in MacOS beta 1 that was preventing the window from getting focus automatically. On beta 2 seems to be resolved. Your code earlier with the .isFocused() check reflects expected behavior more closely. Perhaps you could add another commit for this?

**Comment by LangLangBart** [comment]
- pushed the rquested fix
- as the repo becomes more popular, it may be useful to add a configuration file so that the user can set their preferred hotkey, as currently the <kbd>⌃ Control</kbd> + <kbd>Space</kbd> hotkey is hardcoded
  - Ref: [egoist/devdocs-desktop](https://github.com/egoist/devdocs-desktop/blob/master/app/config.js)

**Comment by SilverMarcs** [comment]
Will do. Thanks!

**Pull request merged**
